# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03da26950588ee569cf041182dc0107c54765bed61f22f82e158733816a62af096da480b3468786b83fb63fc2f06201adde2e5fdf76185b5a94e822f626abc45

test:
  secret_key_base: e714973556a9c4bc15b63604ef99d1f674d9c089e2f0b1dc002faa0892d7ba4cc63dd897d13abf8f4ff89a0531c0d534113bf52cf84e0b63ed52523ad266c9eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
